before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- binary: pdagent
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w
  - -X 'github.com/PagerDuty/pagerduty-agent/pkg/common.Version={{.Version}}'
  - -X 'github.com/PagerDuty/pagerduty-agent/pkg/common.Commit={{.ShortCommit}}'
  - -X 'github.com/PagerDuty/pagerduty-agent/pkg/common.Date={{.Date}}'
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
signs:
- artifacts: all
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  vendor: PagerDuty Inc.
  homepage: https://www.pagerduty.com/
  maintainer: PagerDuty, Inc. <info@pagerduty.com>
  description: PagerDuty's agent daemon.
  license: Apache 2.0
  formats:
    - deb
    - rpm
  # TODO: Pre/post scripts migrated from previous agent.