before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- binary: pdagent
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w
  - -X 'github.com/PagerDuty/pagerduty-agent/pkg/common.Version={{.Version}}'
  - -X 'github.com/PagerDuty/pagerduty-agent/pkg/common.Commit={{.ShortCommit}}'
  - -X 'github.com/PagerDuty/pagerduty-agent/pkg/common.Date={{.Date}}'
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
signs:
- artifacts: all
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
- replacements:
    linux: Linux
    386: i386
    amd64: x86_64
  vendor: PagerDuty Inc.
  homepage: https://www.pagerduty.com/
  maintainer: PagerDuty, Inc. <info@pagerduty.com>
  description: PagerDuty's agent daemon.
  license: Apache 2.0
  formats:
    - deb
    - rpm
  empty_folders:
    - /var/db/pdagent
    - /var/lib/pdagent
    - /var/log/pdagent
    - /var/run/pdagent
  files:
    "init/pdagent.init": "/var/lib/pdagent/scripts/pdagent.init"
    "init/pdagent.service": "/var/lib/pdagent/scripts/pdagent.service"
    "scripts/pd-*": "/usr/local/bin/"
  overrides:
    deb:
      scripts:
        preinstall: "scripts/deb/preinstall.sh"
        postinstall: "scripts/deb/postinstall.sh"
        preremove: "scripts/deb/preremove.sh"
        postremove: "scripts/deb/postremove.sh"
    rpm:
      scripts:
        preinstall: "scripts/rpm/preinstall.sh"
        postinstall: "scripts/rpm/postinstall.sh"
        preremove: "scripts/rpm/preremove.sh"
        postremove: "scripts/rpm/postremove.sh"
