version: 2

orbs:
  git: pagerduty/git@0.0.3

jobs:
  test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - git/rebase_on_main
      - run: go mod download
      - run: make
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
