version: 2.1

orbs:
  git: pagerduty/git@0.0.3

jobs:
  test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - git/rebase_on_main
      - run: go mod download
      - run: make
  release-test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - git/rebase_on_main
      - run:
          name: Setup GPG signing key
          command: |
            echo "$GPG_KEY" | base64 --decode --ignore-garbage | gpg --batch --allow-secret-key-import --import
            gpg --keyid-format LONG --list-secret-keys
            echo $GPG_PASS > ./gpg_pass.txt
      - run:
          name: Cut release
          command: curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish --rm-dist
  release:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - git/rebase_on_main
      - run:
          name: Setup GPG signing key
          command: |
            echo "$GPG_KEY" | base64 --decode --ignore-garbage | gpg --batch --allow-secret-key-import --import
            gpg --keyid-format LONG --list-secret-keys
            echo $GPG_PASS > ./gpg_pass.txt
      - run:
          name: Cut release
          command: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - release-test:
          requires:
            - test
      - release:
          requires:
            - release-test
          # Only run this job on git tag pushes
          filters:
            branches:
              only: main
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
